### ISSUE TITLE
how to install toast-litebird

### ISSUE THREAD

**Issue by mayutom** [hpc4cmb/toast-workshop-tokyo-2020#5]
I attended the TOAST workshop @Tokyo this January.
I would like to install toast-litebird module (https://hpc4cmb.github.io/toast-litebird/intro.html#installation) to my local PC,
and tried to access the link which may have a repository or requirements.txt (https://github.com/hpc4cmb/toast-litebird).
However, I cannot open the website.

How can I install toast-litebird correctly?

**Comment by tskisner** [comment]
Hello @mayutom, I'll add you to that repo (it is private).
